# Generated by Django 4.0.4 on 2022-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile.jpg', upload_to='profile_picture'),
            preserve_default=False,
        ),
    ]
